/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package beans;

/**
 *
 * @author marti
 */
public class Molecules extends javax.swing.JFrame {

    /**
     * Creates new form Molecules
     */
    public Molecules() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timer1 = new magicbeans.Timer();
        timer2 = new magicbeans.Timer();
        molecule1 = new magicbeans.sunw.demo.molecule.Molecule();

        timer1.addTimerListener(new magicbeans.TimerListener() {
            public void timerFired(magicbeans.TimerEvent evt) {
                timer1TimerFired(evt);
            }
        });

        timer2.setDelay(100L);
        timer2.addTimerListener(new magicbeans.TimerListener() {
            public void timerFired(magicbeans.TimerEvent evt) {
                timer2TimerFired(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());
        getContentPane().add(molecule1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void timer1TimerFired(magicbeans.TimerEvent evt) {//GEN-FIRST:event_timer1TimerFired
        molecule1.rotateOnX();
    }//GEN-LAST:event_timer1TimerFired

    private void timer2TimerFired(magicbeans.TimerEvent evt) {//GEN-FIRST:event_timer2TimerFired
        molecule1.rotateOnY();
    }//GEN-LAST:event_timer2TimerFired

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Molecules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Molecules().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private magicbeans.sunw.demo.molecule.Molecule molecule1;
    private magicbeans.Timer timer1;
    private magicbeans.Timer timer2;
    // End of variables declaration//GEN-END:variables
}
