
package learningjava.client.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EchoService", targetNamespace = "http://webservices/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EchoService {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "echoInt", targetNamespace = "http://webservices/", className = "learningjava.client.impl.EchoInt")
    @ResponseWrapper(localName = "echoIntResponse", targetNamespace = "http://webservices/", className = "learningjava.client.impl.EchoIntResponse")
    @Action(input = "http://webservices/EchoService/echoIntRequest", output = "http://webservices/EchoService/echoIntResponse")
    public int echoInt(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "echoString", targetNamespace = "http://webservices/", className = "learningjava.client.impl.EchoString")
    @ResponseWrapper(localName = "echoStringResponse", targetNamespace = "http://webservices/", className = "learningjava.client.impl.EchoStringResponse")
    @Action(input = "http://webservices/EchoService/echoStringRequest", output = "http://webservices/EchoService/echoStringResponse")
    public String echoString(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns learningjava.client.impl.MyObject
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "echoMyObject", targetNamespace = "http://webservices/", className = "learningjava.client.impl.EchoMyObject")
    @ResponseWrapper(localName = "echoMyObjectResponse", targetNamespace = "http://webservices/", className = "learningjava.client.impl.EchoMyObjectResponse")
    @Action(input = "http://webservices/EchoService/echoMyObjectRequest", output = "http://webservices/EchoService/echoMyObjectResponse")
    public MyObject echoMyObject(
        @WebParam(name = "arg0", targetNamespace = "")
        MyObject arg0);

}
